Iter13
dsemenov12/shorturl pull request #13
Opened 2024-11-28 19:05 UTC by dsemenov12

2024-12-02 14:54 UTC, edylcrm requested changes

2024-12-02 14:54 UTC, edylcrm commented on internal/storage/pg/storage.go
> +		tx.Rollback()
Можно просто писать defer tx.Rollback() вне зависимости от того есть ошибка  или нет. Если транзакция была успешна завершена rollback ничего делать не будет и получается чуть читабельней.
```
tx, err := s.conn.BeginTx(ctx, nil)
if err != nil {
     return err
}
defer tx.Rollback()
```
Как-то так. А сейчас если при инициализации транзакции вернется ошибка по идеи будет паника т.к. tx будет nil и rollback будет вызываться у nil

2024-12-02 14:54 UTC, edylcrm commented on internal/handlers/handlers.go
> +var StorageDB *pg.StorageDB
А бы все таки избегал вот таких вот глобальных переменных и использовал dependency injection принцип.

2024-12-03 13:52 UTC, dsemenov12 commented on internal/storage/pg/storage.go
> +		tx.Rollback()
Исправил

2024-12-03 13:53 UTC, dsemenov12 commented on internal/handlers/handlers.go
> +var StorageDB *pg.StorageDB
Убрал использование глобальных переменных, применил DI

2024-12-03 14:55 UTC, edylcrm approved these changes

2024-12-03 14:55 UTC, edylcrm commented on internal/handlers/handlers.go
> +	if config.FlagDatabaseDSN != "" {
Тут было бы еще здорово сделать общий интерфейс для memory storage и pg storage. И в main.go в зависимости от конфигурации (передан ли флаг БД или нет) передавать нужную реализацию. Тогда бы из handlers пропали все if с конфигом и было бы чуть гибче :)

2024-12-06 19:06 UTC, merged