Iter5 Добавлено конфигурирование сервера с помощью переменных окружения
dsemenov12/shorturl pull request #5
Opened 2024-10-23 17:55 UTC by dsemenov12

2024-10-28 09:20 UTC, edylcrm requested changes

2024-10-28 09:20 UTC, edylcrm commented on cmd/shortener/main.go
> +	config.ParseFlags()
Здесь лишние отступы или так github форматирует?

2024-10-28 09:20 UTC, edylcrm commented on internal/handlers/handlers.go
> +	if (err != nil) {
Без () просто err != nil

2024-10-28 09:20 UTC, edylcrm commented on internal/handlers/handlers.go
> +var ShortURLList ShortURLListMap
Глобальное состояние лучше не использовать. Тем более переменная глобальная и доступна из всех пакетов. 
Я бы здесь предложил создать структуру хранения, что-то вроде такого:
```
type storage struct {
    data map[string]string
}

func (s *storage) Get(key string) (string, error) {
    // ...
}

func (s *storage) Set(key, value string) error {
    // ...
}
```
Это так же будет проще закрыть интерфейсом. И также запись в map будет приводить к гонкам. Здесь стоит использовать mutex

2024-10-28 09:20 UTC, edylcrm commented on internal/handlers/handlers.go
> +	http.Redirect(res, req, ShortURLList[shortKey], http.StatusTemporaryRedirect)
А если ключа в map нет, то куда будет redirect?

2024-10-29 12:12 UTC, dsemenov12 commented on cmd/shortener/main.go
> +	config.ParseFlags()
> Здесь лишние отступы или так github форматирует?

github ставит 8 пробелов вместо таба. Попробую настроить VSCode, чтобы ставил пробелы вместо табов

2024-10-29 12:14 UTC, dsemenov12 commented on internal/handlers/handlers.go
> +	if (err != nil) {
Исправлено

2024-10-29 12:15 UTC, dsemenov12 commented on internal/handlers/handlers.go
> +var ShortURLList ShortURLListMap
Заменил глобальную переменную на структуру

2024-10-29 12:17 UTC, dsemenov12 commented on internal/handlers/handlers.go
> +	http.Redirect(res, req, ShortURLList[shortKey], http.StatusTemporaryRedirect)
Добавил проверку на существование элемента с ключом и 404 ошибкой

`
	redirectLink, err := storageObj.Get(shortKey)
	if err != nil {
		http.Error(res, "redirect not found", 404)
	}

`

2024-10-30 06:16 UTC, edylcrm approved these changes

2024-10-30 06:16 UTC, edylcrm commented on internal/handlers/handlers.go
> +type storage struct {
Можно так же вынести в отдельный пакет

2024-11-01 15:11 UTC, merged